export const SET_PROFILE_DATA = 'QUIZ_CARDS/PROFILE/SET-PROFILE-DATA';
export const UPDATE_PROFILE_DATA = 'QUIZ_CARDS/PROFILE/UPDATE-PROFILE-DATA';
export const SET_PROFILE_ERROR = 'QUIZ_CARDS/PROFILE/SET-PROFILE-ERROR';
export const SET_PROFILE_DELETE_DATA = 'QUIZ_CARDS/PROFILE/SET-PROFILE-DELETE-DATA';
