export const LOADING = 'QUIZ_CARDS/APP/SET_LOADING';
export const SET_ERROR_APP = 'QUIZ_CARDS/APP/SET_ERROR_APP';
export const SET_ERROR = 'QUIZ_CARDS/APP/SET_ERROR';
export const SET_INITIALIZED = 'QUIZ_CARDS/APP/SET_INITIALIZED';
