export const SET_CARD = 'QUIZ_CARDS/CARDS/SET_CARD';
export const CLEAR_CARDS = "QUIZ_CARDS/CARDS/CLEAR_CARDS";
export const CHANGE_CURRENT_PAGE = "QUIZ_CARDS/CARDS/CHANGE_CURRENT_PAGE";
export const SORT_CARDS = 'QUIZ_CARDS/CARDS/SORT_CARDS';
export const SET_FILTER_CARDS = 'QUIZ_CARDS/CARDS/SET_FILTER_CARDS';
export const SET_PAGE_COUNT_CARDS = 'QUIZ_CARDS/CARDS/SET_PAGE_COUNT_CARDS';
export const SET_CARDS_GRADE = 'QUIZ_CARDS/CARDS/SET_CARDS_GRADE';